package com.example.feesmanager.ai.actions

import com.example.feesmanager.ai.Priority

/**
 * AiInsight — A structured insight generated by the AI Analyst.
 * Displayed as cards in the Teacher AI interface.
 */
data class AiInsight(
    val title: String,
    val description: String,
    val priority: Priority = Priority.NORMAL,
    val metric: String? = null,        // e.g., "₹12,500" or "23 students"
    val category: InsightCategory = InsightCategory.GENERAL
) {
    enum class InsightCategory {
        FEES,
        ATTENDANCE,
        ISSUES,
        PERFORMANCE,
        GENERAL
    }
}

/**
 * ActionResult — Outcome of executing an AI-suggested action.
 */
data class ActionResult(
    val success: Boolean,
    val message: String,
    val affectedCount: Int = 0
)

/**
 * NotificationPayload — Data for smart AI-triggered notifications.
 */
data class NotificationPayload(
    val title: String,
    val body: String,
    val targetStudentIds: List<String> = emptyList(),
    val targetClassNames: List<String> = emptyList(),
    val priority: Priority = Priority.NORMAL,
    val type: NotificationType = NotificationType.REMINDER
) {
    enum class NotificationType {
        REMINDER,
        ANNOUNCEMENT,
        ALERT,
        INFO
    }
}
